version: "3.1"
services:
    php:
      image: php
      container_name: php-devserver
      working_dir: /project
      volumes:
        - .:/app
      command: php -S 0:8080 /app/public/index.php
      ports:
        - '8080:8080'

    composer:
      image: composer
      container_name: composer
      volumes:
        - .:/app